// src/utils/partsData.js
// This is a local copy of component data for app functionality
// For complete data, see /public/mockData/components.json

export const parts = [
  {
    id: 1,
    name: "AMD Ryzen 5 5600",
    type: "CPU",
    price: 8500,
    retailers: [
      { name: "PC Express", price: 8500, link: "#" },
      { name: "DynaQuest", price: 8700, link: "#" },
    ],
    compatibility: ["AM4"],
    specs: {
      cores: 6,
      threads: 12,
      baseFrequency: "3.5 GHz",
      boostFrequency: "4.4 GHz",
      tdp: 65,
      cache: "35MB",
    },
    image: "/mockData/images/ryzen-5-5600.webp",
    rating: 4.7,
  },
  {
    id: 2,
    name: "Intel Core i5-12400F",
    type: "CPU",
    price: 9500,
    retailers: [
      { name: "PC Hub", price: 9500, link: "#" },
      { name: "DynaQuest", price: 9800, link: "#" },
    ],
    compatibility: ["LGA1700"],
    specs: {
      cores: 6,
      threads: 12,
      baseFrequency: "2.5 GHz",
      boostFrequency: "4.4 GHz",
      tdp: 65,
      cache: "18MB",
    },
    image: "/mockData/images/intel-i5-12400f.webp",
    rating: 4.6,
  },
  {
    id: 101,
    name: "AMD Ryzen 9 7950X",
    type: "CPU",
    price: 34990,
    retailers: [
      { name: "PC Express", price: 34990, link: "#" },
      { name: "DynaQuest", price: 35500, link: "#" },
    ],
    compatibility: ["AM5"],
    specs: {
      cores: 16,
      threads: 32,
      baseFrequency: "4.5 GHz",
      boostFrequency: "5.7 GHz",
      tdp: 170,
      cache: "80MB",
    },
    image: "/mockData/images/ryzen-9-7950x.webp",
    rating: 4.9,
  },
  {
    id: 102,
    name: "Intel Core i9-13900K",
    type: "CPU",
    price: 33500,
    retailers: [
      { name: "PC Hub", price: 33500, link: "#" },
      { name: "DynaQuest", price: 34000, link: "#" },
    ],
    compatibility: ["LGA1700"],
    specs: {
      cores: 24,
      threads: 32,
      baseFrequency: "3.0 GHz",
      boostFrequency: "5.8 GHz",
      tdp: 125,
      cache: "68MB",
    },
    image: "/mockData/images/intel-i9-13900k.webp",
    rating: 4.8,
  },
  {
    id: 103,
    name: "AMD Ryzen 7 7800X3D",
    type: "CPU",
    price: 26500,
    retailers: [
      { name: "PC Express", price: 26500, link: "#" },
      { name: "DynaQuest", price: 27000, link: "#" },
    ],
    compatibility: ["AM5"],
    specs: {
      cores: 8,
      threads: 16,
      baseFrequency: "4.2 GHz",
      boostFrequency: "5.0 GHz",
      tdp: 120,
      cache: "96MB",
    },
    image: "/mockData/images/ryzen-7-7800x3d.webp",
    rating: 4.9,
  },
  {
    id: 104,
    name: "Intel Core i7-14700K",
    type: "CPU",
    price: 26900,
    retailers: [
      { name: "PC Hub", price: 26900, link: "#" },
      { name: "DynaQuest", price: 27500, link: "#" },
    ],
    compatibility: ["LGA1700"],
    specs: {
      cores: 20,
      threads: 28,
      baseFrequency: "3.4 GHz",
      boostFrequency: "5.6 GHz",
      tdp: 125,
      cache: "61MB",
    },
    image: "/mockData/images/intel-i7-14700k.webp",
    rating: 4.7,
  },
  {
    id: 3,
    name: "ASUS B550M-A",
    type: "Motherboard",
    price: 6500,
    retailers: [
      { name: "PC Express", price: 6500, link: "#" },
      { name: "PC Hub", price: 6650, link: "#" },
    ],
    compatibility: ["AM4"],
    specs: {
      chipset: "AMD B550",
      formFactor: "Micro-ATX",
      memorySlots: 4,
      maxMemory: "128GB",
    },
    image: "/mockData/images/asus-b550m.webp",
    rating: 4.4,
  },
  {
    id: 4,
    name: "Gigabyte B660M DS3H",
    type: "Motherboard",
    price: 7000,
    retailers: [
      { name: "DynaQuest", price: 7000, link: "#" },
      { name: "PC Express", price: 7200, link: "#" },
    ],
    compatibility: ["LGA1700"],
    specs: {
      chipset: "Intel B660",
      formFactor: "Micro-ATX",
      memorySlots: 4,
      maxMemory: "128GB",
    },
    image: "/mockData/images/gigabyte-b660m.webp",
    rating: 4.3,
  },
  {
    id: 105,
    name: "ASUS ROG Strix X670E-E Gaming WiFi",
    type: "Motherboard",
    price: 25500,
    retailers: [
      { name: "PC Express", price: 25500, link: "#" },
      { name: "PC Hub", price: 26000, link: "#" },
    ],
    compatibility: ["AM5"],
    specs: {
      chipset: "AMD X670E",
      formFactor: "ATX",
      memorySlots: 4,
      maxMemory: "128GB DDR5",
      pcieSlots: "2 x PCIe 5.0 x16",
    },
    image: "/mockData/images/asus-x670e.webp",
    rating: 4.8,
  },
  {
    id: 106,
    name: "MSI MPG Z790 Gaming Edge WiFi",
    type: "Motherboard",
    price: 23000,
    retailers: [
      { name: "DynaQuest", price: 23000, link: "#" },
      { name: "PC Express", price: 23500, link: "#" },
    ],
    compatibility: ["LGA1700"],
    specs: {
      chipset: "Intel Z790",
      formFactor: "ATX",
      memorySlots: 4,
      maxMemory: "128GB DDR5",
      pcieSlots: "1 x PCIe 5.0 x16, 1 x PCIe 4.0 x16",
    },
    image: "/mockData/images/msi-z790.webp",
    rating: 4.7,
  },
  {
    id: 107,
    name: "Gigabyte X670 AORUS Elite AX",
    type: "Motherboard",
    price: 19500,
    retailers: [
      { name: "PC Hub", price: 19500, link: "#" },
      { name: "DynaQuest", price: 19800, link: "#" },
    ],
    compatibility: ["AM5"],
    specs: {
      chipset: "AMD X670",
      formFactor: "ATX",
      memorySlots: 4,
      maxMemory: "128GB DDR5",
      pcieSlots: "1 x PCIe 5.0 x16, 1 x PCIe 4.0 x16",
    },
    image: "/mockData/images/gigabyte-x670.webp",
    rating: 4.6,
  },
  {
    id: 108,
    name: "ASRock Z790 PG-ITX/TB4",
    type: "Motherboard",
    price: 22500,
    retailers: [
      { name: "PC Express", price: 22500, link: "#" },
      { name: "PC Hub", price: 22900, link: "#" },
    ],
    compatibility: ["LGA1700"],
    specs: {
      chipset: "Intel Z790",
      formFactor: "Mini-ITX",
      memorySlots: 2,
      maxMemory: "64GB DDR5",
      pcieSlots: "1 x PCIe 5.0 x16",
    },
    image: "/mockData/images/asrock-z790-itx.webp",
    rating: 4.5,
  },
  {
    id: 5,
    name: "Kingston FURY Beast 16GB (2x8GB) DDR4-3200",
    type: "Memory",
    price: 3200,
    retailers: [
      { name: "PC Express", price: 3200, link: "#" },
      { name: "DynaQuest", price: 3300, link: "#" },
    ],
    compatibility: ["DDR4"],
    specs: {
      capacity: "16GB (2x8GB)",
      type: "DDR4",
      speed: "3200MHz",
      cas: "CL16",
    },
    image: "/mockData/images/kingston-fury.webp",
    rating: 4.8,
  },
  {
    id: 109,
    name: "G.Skill Trident Z5 RGB 32GB (2x16GB) DDR5-6000",
    type: "Memory",
    price: 12500,
    retailers: [
      { name: "PC Hub", price: 12500, link: "#" },
      { name: "PC Express", price: 12800, link: "#" },
    ],
    compatibility: ["DDR5"],
    specs: {
      capacity: "32GB (2x16GB)",
      type: "DDR5",
      speed: "6000MHz",
      cas: "CL36",
      voltage: "1.35V",
    },
    image: "/mockData/images/gskill-trident-z5.webp",
    rating: 4.9,
  },
  {
    id: 110,
    name: "Corsair Dominator Platinum RGB 32GB (2x16GB) DDR5-5600",
    type: "Memory",
    price: 11900,
    retailers: [
      { name: "DynaQuest", price: 11900, link: "#" },
      { name: "PC Hub", price: 12100, link: "#" },
    ],
    compatibility: ["DDR5"],
    specs: {
      capacity: "32GB (2x16GB)",
      type: "DDR5",
      speed: "5600MHz",
      cas: "CL36",
      voltage: "1.25V",
    },
    image: "/mockData/images/corsair-dominator-ddr5.webp",
    rating: 4.7,
  },
  {
    id: 111,
    name: "Crucial RAM 64GB (2x32GB) DDR5-4800",
    type: "Memory",
    price: 15500,
    retailers: [
      { name: "PC Express", price: 15500, link: "#" },
      { name: "DynaQuest", price: 15800, link: "#" },
    ],
    compatibility: ["DDR5"],
    specs: {
      capacity: "64GB (2x32GB)",
      type: "DDR5",
      speed: "4800MHz",
      cas: "CL40",
      voltage: "1.1V",
    },
    image: "/mockData/images/crucial-ddr5.webp",
    rating: 4.6,
  },
  {
    id: 9,
    name: "MSI GeForce GTX 1660 Super Ventus XS OC",
    type: "GPU",
    price: 11500,
    retailers: [
      { name: "PC Express", price: 11500, link: "#" },
      { name: "DynaQuest", price: 11700, link: "#" },
    ],
    compatibility: ["PCIe"],
    specs: {
      memorySize: "6GB GDDR6",
      coreClock: "1530 MHz",
      boostClock: "1785 MHz",
      tdp: 125,
    },
    image: "/mockData/images/msi-gtx1660.webp",
    rating: 4.6,
  },
  {
    id: 112,
    name: "ASUS ROG Strix GeForce RTX 4090 OC",
    type: "GPU",
    price: 115000,
    retailers: [
      { name: "PC Hub", price: 115000, link: "#" },
      { name: "PC Express", price: 116500, link: "#" },
    ],
    compatibility: ["PCIe 4.0"],
    specs: {
      memorySize: "24GB GDDR6X",
      coreClock: "2235 MHz",
      boostClock: "2640 MHz",
      tdp: 450,
      length: "358mm",
    },
    image: "/mockData/images/asus-rtx4090.webp",
    rating: 4.9,
  },
  {
    id: 113,
    name: "Sapphire NITRO+ AMD Radeon RX 7900 XTX",
    type: "GPU",
    price: 82000,
    retailers: [
      { name: "DynaQuest", price: 82000, link: "#" },
      { name: "PC Hub", price: 83500, link: "#" },
    ],
    compatibility: ["PCIe 4.0"],
    specs: {
      memorySize: "24GB GDDR6",
      coreClock: "1855 MHz",
      boostClock: "2455 MHz",
      tdp: 355,
      length: "315mm",
    },
    image: "/mockData/images/sapphire-rx7900xtx.webp",
    rating: 4.7,
  },
  {
    id: 114,
    name: "MSI Gaming X Trio GeForce RTX 4070 Ti",
    type: "GPU",
    price: 55000,
    retailers: [
      { name: "PC Express", price: 55000, link: "#" },
      { name: "DynaQuest", price: 56000, link: "#" },
    ],
    compatibility: ["PCIe 4.0"],
    specs: {
      memorySize: "12GB GDDR6X",
      coreClock: "2310 MHz",
      boostClock: "2760 MHz",
      tdp: 285,
      length: "337mm",
    },
    image: "/mockData/images/msi-rtx4070ti.webp",
    rating: 4.8,
  },
  {
    id: 115,
    name: "Gigabyte AORUS Radeon RX 6800 XT Master",
    type: "GPU",
    price: 45000,
    retailers: [
      { name: "PC Hub", price: 45000, link: "#" },
      { name: "PC Express", price: 45800, link: "#" },
    ],
    compatibility: ["PCIe 4.0"],
    specs: {
      memorySize: "16GB GDDR6",
      coreClock: "1825 MHz",
      boostClock: "2285 MHz",
      tdp: 300,
      length: "320mm",
    },
    image: "/mockData/images/gigabyte-rx6800xt.webp",
    rating: 4.7,
  },
  // Storage components
  {
    id: 116,
    name: "Samsung 990 PRO 2TB M.2 NVMe PCIe 4.0 SSD",
    type: "Storage",
    price: 13500,
    retailers: [
      { name: "PC Hub", price: 13500, link: "#" },
      { name: "DynaQuest", price: 13800, link: "#" },
    ],
    compatibility: ["M.2 PCIe"],
    specs: {
      capacity: "2TB",
      interface: "M.2 PCIe Gen4 x4",
      readSpeed: "7450 MB/s",
      writeSpeed: "6900 MB/s",
      tbw: "1200TB",
    },
    image: "/mockData/images/samsung-990-pro.webp",
    rating: 4.9,
  },
  {
    id: 117,
    name: "Western Digital WD_BLACK SN850X 1TB NVMe SSD",
    type: "Storage",
    price: 8200,
    retailers: [
      { name: "PC Express", price: 8200, link: "#" },
      { name: "PC Hub", price: 8400, link: "#" },
    ],
    compatibility: ["M.2 PCIe"],
    specs: {
      capacity: "1TB",
      interface: "M.2 PCIe Gen4 x4",
      readSpeed: "7300 MB/s",
      writeSpeed: "6300 MB/s",
      tbw: "600TB",
    },
    image: "/mockData/images/wd-sn850x.webp",
    rating: 4.8,
  },
  {
    id: 118,
    name: "Crucial P5 Plus 2TB PCIe M.2 SSD",
    type: "Storage",
    price: 10500,
    retailers: [
      { name: "DynaQuest", price: 10500, link: "#" },
      { name: "PC Express", price: 10700, link: "#" },
    ],
    compatibility: ["M.2 PCIe"],
    specs: {
      capacity: "2TB",
      interface: "M.2 PCIe Gen4 x4",
      readSpeed: "6600 MB/s",
      writeSpeed: "5000 MB/s",
      tbw: "1200TB",
    },
    image: "/mockData/images/crucial-p5-plus.webp",
    rating: 4.7,
  },
  // PSU components
  {
    id: 119,
    name: "Corsair RM850x (2021)",
    type: "PSU",
    price: 8500,
    retailers: [
      { name: "PC Hub", price: 8500, link: "#" },
      { name: "DynaQuest", price: 8700, link: "#" },
    ],
    compatibility: ["ATX"],
    specs: {
      wattage: "850W",
      efficiency: "80+ Gold",
      modular: true,
      formFactor: "ATX",
    },
    image: "/mockData/images/corsair-rm850x.webp",
    rating: 4.9,
  },
  {
    id: 120,
    name: "be quiet! Straight Power 11 750W",
    type: "PSU",
    price: 9200,
    retailers: [
      { name: "PC Express", price: 9200, link: "#" },
      { name: "PC Hub", price: 9400, link: "#" },
    ],
    compatibility: ["ATX"],
    specs: {
      wattage: "750W",
      efficiency: "80+ Gold",
      modular: true,
      formFactor: "ATX",
    },
    image: "/mockData/images/bequiet-straight-power.webp",
    rating: 4.8,
  },
  // Case components
  {
    id: 121,
    name: "Lian Li O11 Dynamic EVO",
    type: "Case",
    price: 8900,
    retailers: [
      { name: "PC Hub", price: 8900, link: "#" },
      { name: "DynaQuest", price: 9100, link: "#" },
    ],
    compatibility: ["ATX", "Micro-ATX", "Mini-ITX"],
    specs: {
      formFactor: "Mid Tower",
      dimensions: "450mm x 285mm x 459mm",
      maxGPULength: "420mm",
      maxCPUCoolerHeight: "167mm",
    },
    image: "/mockData/images/lian-li-o11.webp",
    rating: 4.9,
  },
  {
    id: 122,
    name: "Fractal Design Torrent Compact",
    type: "Case",
    price: 7500,
    retailers: [
      { name: "PC Express", price: 7500, link: "#" },
      { name: "PC Hub", price: 7700, link: "#" },
    ],
    compatibility: ["ATX", "Micro-ATX", "Mini-ITX"],
    specs: {
      formFactor: "Mid Tower",
      dimensions: "426mm x 223mm x 467mm",
      maxGPULength: "330mm",
      maxCPUCoolerHeight: "175mm",
    },
    image: "/mockData/images/fractal-torrent.webp",
    rating: 4.8,
  },
  // CPU Cooler components
  {
    id: 123,
    name: "Noctua NH-D15 chromax.black",
    type: "CPU Cooler",
    price: 5800,
    retailers: [
      { name: "PC Hub", price: 5800, link: "#" },
      { name: "DynaQuest", price: 5950, link: "#" },
    ],
    compatibility: ["AM4", "AM5", "LGA1700", "LGA1200"],
    specs: {
      coolerType: "Air",
      fanSize: "140mm",
      height: "165mm",
      noise: "24.6 dBA",
    },
    image: "/mockData/images/noctua-nh-d15.webp",
    rating: 4.9,
  },
  {
    id: 124,
    name: "ARCTIC Liquid Freezer II 360",
    type: "CPU Cooler",
    price: 6900,
    retailers: [
      { name: "PC Express", price: 6900, link: "#" },
      { name: "PC Hub", price: 7100, link: "#" },
    ],
    compatibility: ["AM4", "AM5", "LGA1700", "LGA1200"],
    specs: {
      coolerType: "AIO Liquid",
      radiatorSize: "360mm",
      fanSize: "120mm x 3",
      noise: "0.3 Sone",
    },
    image: "/mockData/images/arctic-liquid-freezer.webp",
    rating: 4.8,
  },
  // Fans components
  {
    id: 125,
    name: "Noctua NF-A12x25 PWM (5-pack)",
    type: "Fans",
    price: 7500,
    retailers: [
      { name: "PC Hub", price: 7500, link: "#" },
      { name: "PC Express", price: 7700, link: "#" },
    ],
    compatibility: ["120mm"],
    specs: {
      fanSize: "120mm",
      rpm: "450-2000 RPM",
      airflow: "60.1 CFM",
      noise: "22.6 dBA",
    },
    image: "/mockData/images/noctua-nf-a12x25.webp",
    rating: 4.9,
  },
  {
    id: 126,
    name: "Corsair iCUE QL120 RGB (3-pack)",
    type: "Fans",
    price: 5500,
    retailers: [
      { name: "DynaQuest", price: 5500, link: "#" },
      { name: "PC Hub", price: 5700, link: "#" },
    ],
    compatibility: ["120mm"],
    specs: {
      fanSize: "120mm",
      rpm: "525-1500 RPM",
      airflow: "41.8 CFM",
      noise: "26 dBA",
      lighting: "RGB",
    },
    image: "/mockData/images/corsair-ql120.webp",
    rating: 4.7,
  },
  // Monitor components
  {
    id: 127,
    name: "Dell S2721DGF",
    type: "Monitor",
    price: 27500,
    retailers: [
      { name: "PC Express", price: 27500, link: "#" },
      { name: "DynaQuest", price: 27900, link: "#" },
    ],
    compatibility: ["DisplayPort", "HDMI"],
    specs: {
      size: "27 inch",
      resolution: "2560x1440 (WQHD)",
      refreshRate: "165Hz",
      panelType: "Nano IPS",
      responseTime: "1ms GtG",
    },
    image: "/mockData/images/dell-s2721dgf.webp",
    rating: 4.8,
  },
  {
    id: 128,
    name: "ASUS ROG Swift PG32UQ",
    type: "Monitor",
    price: 49900,
    retailers: [
      { name: "PC Hub", price: 49900, link: "#" },
      { name: "PC Express", price: 50500, link: "#" },
    ],
    compatibility: ["DisplayPort", "HDMI 2.1"],
    specs: {
      size: "32 inch",
      resolution: "3840x2160 (4K UHD)",
      refreshRate: "144Hz",
      panelType: "IPS",
      responseTime: "1ms GTG",
      hdr: "DisplayHDR 600",
    },
    image: "/mockData/images/asus-pg32uq.webp",
    rating: 4.9,
  },
];
